/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-12 at 00:01:21 UTC 
 * Modify at your own risk.
 */

package com.example.remindme.storeeventendpoint;

/**
 * Service definition for Storeeventendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StoreeventendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Storeeventendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the storeeventendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://androidremindme.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "storeeventendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Storeeventendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Storeeventendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getStoreEvent".
   *
   * This request holds the parameters needed by the storeeventendpoint server.  After setting any
   * optional parameters, call the {@link GetStoreEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetStoreEvent getStoreEvent(java.lang.Long id) throws java.io.IOException {
    GetStoreEvent result = new GetStoreEvent(id);
    initialize(result);
    return result;
  }

  public class GetStoreEvent extends StoreeventendpointRequest<com.example.remindme.storeeventendpoint.model.StoreEvent> {

    private static final String REST_PATH = "storeevent/{id}";

    /**
     * Create a request for the method "getStoreEvent".
     *
     * This request holds the parameters needed by the the storeeventendpoint server.  After setting
     * any optional parameters, call the {@link GetStoreEvent#execute()} method to invoke the remote
     * operation. <p> {@link GetStoreEvent#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetStoreEvent(java.lang.Long id) {
      super(Storeeventendpoint.this, "GET", REST_PATH, null, com.example.remindme.storeeventendpoint.model.StoreEvent.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetStoreEvent setAlt(java.lang.String alt) {
      return (GetStoreEvent) super.setAlt(alt);
    }

    @Override
    public GetStoreEvent setFields(java.lang.String fields) {
      return (GetStoreEvent) super.setFields(fields);
    }

    @Override
    public GetStoreEvent setKey(java.lang.String key) {
      return (GetStoreEvent) super.setKey(key);
    }

    @Override
    public GetStoreEvent setOauthToken(java.lang.String oauthToken) {
      return (GetStoreEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public GetStoreEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetStoreEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetStoreEvent setQuotaUser(java.lang.String quotaUser) {
      return (GetStoreEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetStoreEvent setUserIp(java.lang.String userIp) {
      return (GetStoreEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetStoreEvent setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetStoreEvent set(String parameterName, Object value) {
      return (GetStoreEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertStoreEvent".
   *
   * This request holds the parameters needed by the storeeventendpoint server.  After setting any
   * optional parameters, call the {@link InsertStoreEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.remindme.storeeventendpoint.model.StoreEvent}
   * @return the request
   */
  public InsertStoreEvent insertStoreEvent(com.example.remindme.storeeventendpoint.model.StoreEvent content) throws java.io.IOException {
    InsertStoreEvent result = new InsertStoreEvent(content);
    initialize(result);
    return result;
  }

  public class InsertStoreEvent extends StoreeventendpointRequest<com.example.remindme.storeeventendpoint.model.StoreEvent> {

    private static final String REST_PATH = "storeevent";

    /**
     * Create a request for the method "insertStoreEvent".
     *
     * This request holds the parameters needed by the the storeeventendpoint server.  After setting
     * any optional parameters, call the {@link InsertStoreEvent#execute()} method to invoke the
     * remote operation. <p> {@link InsertStoreEvent#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.example.remindme.storeeventendpoint.model.StoreEvent}
     * @since 1.13
     */
    protected InsertStoreEvent(com.example.remindme.storeeventendpoint.model.StoreEvent content) {
      super(Storeeventendpoint.this, "POST", REST_PATH, content, com.example.remindme.storeeventendpoint.model.StoreEvent.class);
    }

    @Override
    public InsertStoreEvent setAlt(java.lang.String alt) {
      return (InsertStoreEvent) super.setAlt(alt);
    }

    @Override
    public InsertStoreEvent setFields(java.lang.String fields) {
      return (InsertStoreEvent) super.setFields(fields);
    }

    @Override
    public InsertStoreEvent setKey(java.lang.String key) {
      return (InsertStoreEvent) super.setKey(key);
    }

    @Override
    public InsertStoreEvent setOauthToken(java.lang.String oauthToken) {
      return (InsertStoreEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertStoreEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertStoreEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertStoreEvent setQuotaUser(java.lang.String quotaUser) {
      return (InsertStoreEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertStoreEvent setUserIp(java.lang.String userIp) {
      return (InsertStoreEvent) super.setUserIp(userIp);
    }

    @Override
    public InsertStoreEvent set(String parameterName, Object value) {
      return (InsertStoreEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listStoreEvent".
   *
   * This request holds the parameters needed by the storeeventendpoint server.  After setting any
   * optional parameters, call the {@link ListStoreEvent#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListStoreEvent listStoreEvent() throws java.io.IOException {
    ListStoreEvent result = new ListStoreEvent();
    initialize(result);
    return result;
  }

  public class ListStoreEvent extends StoreeventendpointRequest<com.example.remindme.storeeventendpoint.model.CollectionResponseStoreEvent> {

    private static final String REST_PATH = "storeevent";

    /**
     * Create a request for the method "listStoreEvent".
     *
     * This request holds the parameters needed by the the storeeventendpoint server.  After setting
     * any optional parameters, call the {@link ListStoreEvent#execute()} method to invoke the remote
     * operation. <p> {@link ListStoreEvent#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListStoreEvent() {
      super(Storeeventendpoint.this, "GET", REST_PATH, null, com.example.remindme.storeeventendpoint.model.CollectionResponseStoreEvent.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListStoreEvent setAlt(java.lang.String alt) {
      return (ListStoreEvent) super.setAlt(alt);
    }

    @Override
    public ListStoreEvent setFields(java.lang.String fields) {
      return (ListStoreEvent) super.setFields(fields);
    }

    @Override
    public ListStoreEvent setKey(java.lang.String key) {
      return (ListStoreEvent) super.setKey(key);
    }

    @Override
    public ListStoreEvent setOauthToken(java.lang.String oauthToken) {
      return (ListStoreEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public ListStoreEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListStoreEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListStoreEvent setQuotaUser(java.lang.String quotaUser) {
      return (ListStoreEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListStoreEvent setUserIp(java.lang.String userIp) {
      return (ListStoreEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListStoreEvent setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListStoreEvent setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListStoreEvent set(String parameterName, Object value) {
      return (ListStoreEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeStoreEvent".
   *
   * This request holds the parameters needed by the storeeventendpoint server.  After setting any
   * optional parameters, call the {@link RemoveStoreEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveStoreEvent removeStoreEvent(java.lang.Long id) throws java.io.IOException {
    RemoveStoreEvent result = new RemoveStoreEvent(id);
    initialize(result);
    return result;
  }

  public class RemoveStoreEvent extends StoreeventendpointRequest<Void> {

    private static final String REST_PATH = "storeevent/{id}";

    /**
     * Create a request for the method "removeStoreEvent".
     *
     * This request holds the parameters needed by the the storeeventendpoint server.  After setting
     * any optional parameters, call the {@link RemoveStoreEvent#execute()} method to invoke the
     * remote operation. <p> {@link RemoveStoreEvent#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveStoreEvent(java.lang.Long id) {
      super(Storeeventendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveStoreEvent setAlt(java.lang.String alt) {
      return (RemoveStoreEvent) super.setAlt(alt);
    }

    @Override
    public RemoveStoreEvent setFields(java.lang.String fields) {
      return (RemoveStoreEvent) super.setFields(fields);
    }

    @Override
    public RemoveStoreEvent setKey(java.lang.String key) {
      return (RemoveStoreEvent) super.setKey(key);
    }

    @Override
    public RemoveStoreEvent setOauthToken(java.lang.String oauthToken) {
      return (RemoveStoreEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveStoreEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveStoreEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveStoreEvent setQuotaUser(java.lang.String quotaUser) {
      return (RemoveStoreEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveStoreEvent setUserIp(java.lang.String userIp) {
      return (RemoveStoreEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveStoreEvent setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveStoreEvent set(String parameterName, Object value) {
      return (RemoveStoreEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStoreEvent".
   *
   * This request holds the parameters needed by the storeeventendpoint server.  After setting any
   * optional parameters, call the {@link UpdateStoreEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.remindme.storeeventendpoint.model.StoreEvent}
   * @return the request
   */
  public UpdateStoreEvent updateStoreEvent(com.example.remindme.storeeventendpoint.model.StoreEvent content) throws java.io.IOException {
    UpdateStoreEvent result = new UpdateStoreEvent(content);
    initialize(result);
    return result;
  }

  public class UpdateStoreEvent extends StoreeventendpointRequest<com.example.remindme.storeeventendpoint.model.StoreEvent> {

    private static final String REST_PATH = "storeevent";

    /**
     * Create a request for the method "updateStoreEvent".
     *
     * This request holds the parameters needed by the the storeeventendpoint server.  After setting
     * any optional parameters, call the {@link UpdateStoreEvent#execute()} method to invoke the
     * remote operation. <p> {@link UpdateStoreEvent#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.example.remindme.storeeventendpoint.model.StoreEvent}
     * @since 1.13
     */
    protected UpdateStoreEvent(com.example.remindme.storeeventendpoint.model.StoreEvent content) {
      super(Storeeventendpoint.this, "PUT", REST_PATH, content, com.example.remindme.storeeventendpoint.model.StoreEvent.class);
    }

    @Override
    public UpdateStoreEvent setAlt(java.lang.String alt) {
      return (UpdateStoreEvent) super.setAlt(alt);
    }

    @Override
    public UpdateStoreEvent setFields(java.lang.String fields) {
      return (UpdateStoreEvent) super.setFields(fields);
    }

    @Override
    public UpdateStoreEvent setKey(java.lang.String key) {
      return (UpdateStoreEvent) super.setKey(key);
    }

    @Override
    public UpdateStoreEvent setOauthToken(java.lang.String oauthToken) {
      return (UpdateStoreEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStoreEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStoreEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStoreEvent setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStoreEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStoreEvent setUserIp(java.lang.String userIp) {
      return (UpdateStoreEvent) super.setUserIp(userIp);
    }

    @Override
    public UpdateStoreEvent set(String parameterName, Object value) {
      return (UpdateStoreEvent) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Storeeventendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Storeeventendpoint}. */
    @Override
    public Storeeventendpoint build() {
      return new Storeeventendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StoreeventendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStoreeventendpointRequestInitializer(
        StoreeventendpointRequestInitializer storeeventendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(storeeventendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
