/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-12 at 00:01:29 UTC 
 * Modify at your own risk.
 */

package com.example.remindme.storedataendpoint.model;

/**
 * Model definition for StoreData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storedataendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String event;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String group;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groupEmail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEvent() {
    return event;
  }

  /**
   * @param event event or {@code null} for none
   */
  public StoreData setEvent(java.lang.String event) {
    this.event = event;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroup() {
    return group;
  }

  /**
   * @param group group or {@code null} for none
   */
  public StoreData setGroup(java.lang.String group) {
    this.group = group;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroupEmail() {
    return groupEmail;
  }

  /**
   * @param groupEmail groupEmail or {@code null} for none
   */
  public StoreData setGroupEmail(java.lang.String groupEmail) {
    this.groupEmail = groupEmail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public StoreData setKey(Key key) {
    this.key = key;
    return this;
  }

  @Override
  public StoreData set(String fieldName, Object value) {
    return (StoreData) super.set(fieldName, value);
  }

  @Override
  public StoreData clone() {
    return (StoreData) super.clone();
  }

}
