/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-12 at 00:01:29 UTC 
 * Modify at your own risk.
 */

package com.example.remindme.storedataendpoint;

/**
 * Service definition for Storedataendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StoredataendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Storedataendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the storedataendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://androidremindme.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "storedataendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Storedataendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Storedataendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getStoreData".
   *
   * This request holds the parameters needed by the storedataendpoint server.  After setting any
   * optional parameters, call the {@link GetStoreData#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetStoreData getStoreData(java.lang.Long id) throws java.io.IOException {
    GetStoreData result = new GetStoreData(id);
    initialize(result);
    return result;
  }

  public class GetStoreData extends StoredataendpointRequest<com.example.remindme.storedataendpoint.model.StoreData> {

    private static final String REST_PATH = "storedata/{id}";

    /**
     * Create a request for the method "getStoreData".
     *
     * This request holds the parameters needed by the the storedataendpoint server.  After setting
     * any optional parameters, call the {@link GetStoreData#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetStoreData#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetStoreData(java.lang.Long id) {
      super(Storedataendpoint.this, "GET", REST_PATH, null, com.example.remindme.storedataendpoint.model.StoreData.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetStoreData setAlt(java.lang.String alt) {
      return (GetStoreData) super.setAlt(alt);
    }

    @Override
    public GetStoreData setFields(java.lang.String fields) {
      return (GetStoreData) super.setFields(fields);
    }

    @Override
    public GetStoreData setKey(java.lang.String key) {
      return (GetStoreData) super.setKey(key);
    }

    @Override
    public GetStoreData setOauthToken(java.lang.String oauthToken) {
      return (GetStoreData) super.setOauthToken(oauthToken);
    }

    @Override
    public GetStoreData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetStoreData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetStoreData setQuotaUser(java.lang.String quotaUser) {
      return (GetStoreData) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetStoreData setUserIp(java.lang.String userIp) {
      return (GetStoreData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetStoreData setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetStoreData set(String parameterName, Object value) {
      return (GetStoreData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertStoreData".
   *
   * This request holds the parameters needed by the storedataendpoint server.  After setting any
   * optional parameters, call the {@link InsertStoreData#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.remindme.storedataendpoint.model.StoreData}
   * @return the request
   */
  public InsertStoreData insertStoreData(com.example.remindme.storedataendpoint.model.StoreData content) throws java.io.IOException {
    InsertStoreData result = new InsertStoreData(content);
    initialize(result);
    return result;
  }

  public class InsertStoreData extends StoredataendpointRequest<com.example.remindme.storedataendpoint.model.StoreData> {

    private static final String REST_PATH = "storedata";

    /**
     * Create a request for the method "insertStoreData".
     *
     * This request holds the parameters needed by the the storedataendpoint server.  After setting
     * any optional parameters, call the {@link InsertStoreData#execute()} method to invoke the remote
     * operation. <p> {@link InsertStoreData#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.remindme.storedataendpoint.model.StoreData}
     * @since 1.13
     */
    protected InsertStoreData(com.example.remindme.storedataendpoint.model.StoreData content) {
      super(Storedataendpoint.this, "POST", REST_PATH, content, com.example.remindme.storedataendpoint.model.StoreData.class);
    }

    @Override
    public InsertStoreData setAlt(java.lang.String alt) {
      return (InsertStoreData) super.setAlt(alt);
    }

    @Override
    public InsertStoreData setFields(java.lang.String fields) {
      return (InsertStoreData) super.setFields(fields);
    }

    @Override
    public InsertStoreData setKey(java.lang.String key) {
      return (InsertStoreData) super.setKey(key);
    }

    @Override
    public InsertStoreData setOauthToken(java.lang.String oauthToken) {
      return (InsertStoreData) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertStoreData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertStoreData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertStoreData setQuotaUser(java.lang.String quotaUser) {
      return (InsertStoreData) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertStoreData setUserIp(java.lang.String userIp) {
      return (InsertStoreData) super.setUserIp(userIp);
    }

    @Override
    public InsertStoreData set(String parameterName, Object value) {
      return (InsertStoreData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listStoreData".
   *
   * This request holds the parameters needed by the storedataendpoint server.  After setting any
   * optional parameters, call the {@link ListStoreData#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListStoreData listStoreData() throws java.io.IOException {
    ListStoreData result = new ListStoreData();
    initialize(result);
    return result;
  }

  public class ListStoreData extends StoredataendpointRequest<com.example.remindme.storedataendpoint.model.CollectionResponseStoreData> {

    private static final String REST_PATH = "storedata";

    /**
     * Create a request for the method "listStoreData".
     *
     * This request holds the parameters needed by the the storedataendpoint server.  After setting
     * any optional parameters, call the {@link ListStoreData#execute()} method to invoke the remote
     * operation. <p> {@link ListStoreData#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListStoreData() {
      super(Storedataendpoint.this, "GET", REST_PATH, null, com.example.remindme.storedataendpoint.model.CollectionResponseStoreData.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListStoreData setAlt(java.lang.String alt) {
      return (ListStoreData) super.setAlt(alt);
    }

    @Override
    public ListStoreData setFields(java.lang.String fields) {
      return (ListStoreData) super.setFields(fields);
    }

    @Override
    public ListStoreData setKey(java.lang.String key) {
      return (ListStoreData) super.setKey(key);
    }

    @Override
    public ListStoreData setOauthToken(java.lang.String oauthToken) {
      return (ListStoreData) super.setOauthToken(oauthToken);
    }

    @Override
    public ListStoreData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListStoreData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListStoreData setQuotaUser(java.lang.String quotaUser) {
      return (ListStoreData) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListStoreData setUserIp(java.lang.String userIp) {
      return (ListStoreData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListStoreData setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListStoreData setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListStoreData set(String parameterName, Object value) {
      return (ListStoreData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeStoreData".
   *
   * This request holds the parameters needed by the storedataendpoint server.  After setting any
   * optional parameters, call the {@link RemoveStoreData#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveStoreData removeStoreData(java.lang.Long id) throws java.io.IOException {
    RemoveStoreData result = new RemoveStoreData(id);
    initialize(result);
    return result;
  }

  public class RemoveStoreData extends StoredataendpointRequest<Void> {

    private static final String REST_PATH = "storedata/{id}";

    /**
     * Create a request for the method "removeStoreData".
     *
     * This request holds the parameters needed by the the storedataendpoint server.  After setting
     * any optional parameters, call the {@link RemoveStoreData#execute()} method to invoke the remote
     * operation. <p> {@link RemoveStoreData#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveStoreData(java.lang.Long id) {
      super(Storedataendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveStoreData setAlt(java.lang.String alt) {
      return (RemoveStoreData) super.setAlt(alt);
    }

    @Override
    public RemoveStoreData setFields(java.lang.String fields) {
      return (RemoveStoreData) super.setFields(fields);
    }

    @Override
    public RemoveStoreData setKey(java.lang.String key) {
      return (RemoveStoreData) super.setKey(key);
    }

    @Override
    public RemoveStoreData setOauthToken(java.lang.String oauthToken) {
      return (RemoveStoreData) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveStoreData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveStoreData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveStoreData setQuotaUser(java.lang.String quotaUser) {
      return (RemoveStoreData) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveStoreData setUserIp(java.lang.String userIp) {
      return (RemoveStoreData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveStoreData setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveStoreData set(String parameterName, Object value) {
      return (RemoveStoreData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStoreData".
   *
   * This request holds the parameters needed by the storedataendpoint server.  After setting any
   * optional parameters, call the {@link UpdateStoreData#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.remindme.storedataendpoint.model.StoreData}
   * @return the request
   */
  public UpdateStoreData updateStoreData(com.example.remindme.storedataendpoint.model.StoreData content) throws java.io.IOException {
    UpdateStoreData result = new UpdateStoreData(content);
    initialize(result);
    return result;
  }

  public class UpdateStoreData extends StoredataendpointRequest<com.example.remindme.storedataendpoint.model.StoreData> {

    private static final String REST_PATH = "storedata";

    /**
     * Create a request for the method "updateStoreData".
     *
     * This request holds the parameters needed by the the storedataendpoint server.  After setting
     * any optional parameters, call the {@link UpdateStoreData#execute()} method to invoke the remote
     * operation. <p> {@link UpdateStoreData#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.remindme.storedataendpoint.model.StoreData}
     * @since 1.13
     */
    protected UpdateStoreData(com.example.remindme.storedataendpoint.model.StoreData content) {
      super(Storedataendpoint.this, "PUT", REST_PATH, content, com.example.remindme.storedataendpoint.model.StoreData.class);
    }

    @Override
    public UpdateStoreData setAlt(java.lang.String alt) {
      return (UpdateStoreData) super.setAlt(alt);
    }

    @Override
    public UpdateStoreData setFields(java.lang.String fields) {
      return (UpdateStoreData) super.setFields(fields);
    }

    @Override
    public UpdateStoreData setKey(java.lang.String key) {
      return (UpdateStoreData) super.setKey(key);
    }

    @Override
    public UpdateStoreData setOauthToken(java.lang.String oauthToken) {
      return (UpdateStoreData) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStoreData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStoreData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStoreData setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStoreData) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStoreData setUserIp(java.lang.String userIp) {
      return (UpdateStoreData) super.setUserIp(userIp);
    }

    @Override
    public UpdateStoreData set(String parameterName, Object value) {
      return (UpdateStoreData) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Storedataendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Storedataendpoint}. */
    @Override
    public Storedataendpoint build() {
      return new Storedataendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StoredataendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStoredataendpointRequestInitializer(
        StoredataendpointRequestInitializer storedataendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(storedataendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
