/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-12 at 00:01:21 UTC 
 * Modify at your own risk.
 */

package com.example.remindme.storeeventendpoint.model;

/**
 * Model definition for StoreEvent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the storeeventendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class StoreEvent extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eventDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eventID;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eventName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eventTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String group;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String location;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public StoreEvent setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEventDate() {
    return eventDate;
  }

  /**
   * @param eventDate eventDate or {@code null} for none
   */
  public StoreEvent setEventDate(java.lang.String eventDate) {
    this.eventDate = eventDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEventID() {
    return eventID;
  }

  /**
   * @param eventID eventID or {@code null} for none
   */
  public StoreEvent setEventID(java.lang.String eventID) {
    this.eventID = eventID;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEventName() {
    return eventName;
  }

  /**
   * @param eventName eventName or {@code null} for none
   */
  public StoreEvent setEventName(java.lang.String eventName) {
    this.eventName = eventName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEventTime() {
    return eventTime;
  }

  /**
   * @param eventTime eventTime or {@code null} for none
   */
  public StoreEvent setEventTime(java.lang.String eventTime) {
    this.eventTime = eventTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroup() {
    return group;
  }

  /**
   * @param group group or {@code null} for none
   */
  public StoreEvent setGroup(java.lang.String group) {
    this.group = group;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public StoreEvent setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public StoreEvent setLocation(java.lang.String location) {
    this.location = location;
    return this;
  }

  @Override
  public StoreEvent set(String fieldName, Object value) {
    return (StoreEvent) super.set(fieldName, value);
  }

  @Override
  public StoreEvent clone() {
    return (StoreEvent) super.clone();
  }

}
